#!/bin/bash

scriptPath=$(readlink -f $(dirname $0))

read -p "Project Name ? " PROJECTNAME
read -ep "Project Path ? " PROJECTPATH

[ -d "$PROJECTPATH/$PROJECTNAME" ] && echo "A project with this name already exist" >&2 && exit 1

PROJECTPATH=$(readlink -f $PROJECTPATH)/$PROJECTNAME
mkdir $PROJECTPATH
mkdir "$PROJECTPATH/library"


butterflyPath=''
while [ -z $butterflyPath ] || [ ! -d $butterflyPath ]
do
    read -ep "Butterfly Path ? " butterflyPath
    butterflyPath=$(readlink -f $butterflyPath)
done

useDB=''
while [ "$useDB" != 'y' ] && [ "$useDB" != 'n' ]
do
    read -ep "Use sql database (y/n) ? " useDB
done

if [ "$useDB" == 'y' ]
then
    sgbd=''
    while [ "$sgbd" != "pgsql" ] #&& [ "$sgbd" != "mysql" ]
    do
        read -ep "sgbd (mysql/pgsql) ? " sgbd
    done
    dbName=''
    while [ -z "$dbName" ]
    do
        read -ep "dbName ? " dbName
    done
    dbUser=''
    while [ -z "$dbUser" ]
    do
        read -ep "Db user ? " dbUser
    done
    dbPass=''
    while [ -z "$dbPass" ]
    do
        read -esp "Db password ? " dbPass
    done
    echo ''
    dbHost=''
    while [ -z "$dbHost" ]
    do
        read -ep "Db host ? " dbHost
    done
    #handle mysql sgbd
    echo "CREATE DATABASE $dbName;" > /tmp/butterflyquery
    less ~/workspace/web/ButterflyInstaller/db.sql >> /tmp/butterflyquery
    psql -U $dbUser -h $dbHost $dbName < /tmp/butterflyquery
    rm /tmp/butterflyquery
fi

ln -s $butterflyPath/library/Butterfly Butterfly

mkdir $PROJECTPATH/www
if [ $useDB == 'y' ]
then
    cp $scriptPath/www/index.php $PROJECTPATH/www/index.php
else
    cp $scriptPath/www/index-nodb.php $PROJECTPATH/www/index.php
fi
perl -pi -e "s/%PROJECTNAME%/$PROJECTNAME/g" $PROJECTPATH/www/index.php
cp -r $scriptPath/www/styles $PROJECTPATH/www/


mkdir -p $PROJECTPATH/site/components/modules/
cp -r $scriptPath/site/components/modules/Default $scriptPath/site/components/modules/Error $PROJECTPATH/site/components/modules

mkdir -p $PROJECTPATH/site/components/plugins

mkdir -p $PROJECTPATH/site/components/widgets
cp -r $scriptPath/site/components/widgets/Header $PROJECTPATH/site/components/widgets

mkdir -p $PROJECTPATH/site/config
if [ $useDB == 'n' ]
then
    cp $scriptPath/site/config/config-nodb.ini $PROJECTPATH/site/config/config.ini
else
    cp $scriptPath/site/config/config-db.ini $PROJECTPATH/site/config/config.ini
    perl -pi -e "s#%SGBD%#$sgbd#g" $PROJECTPATH/site/config/config.ini
    perl -pi -e "s#%DBHOST%#$dbHost#g" $PROJECTPATH/site/config/config.ini
    perl -pi -e "s#%DBNAME#$dbName#g" $PROJECTPATH/site/config/config.ini
    perl -pi -e "s#%DBUSER%#$dbUser#g" $PROJECTPATH/site/config/config.ini
    perl -pi -e "s#%DBPASS%#$dbPass#g" $PROJECTPATH/site/config/config.ini
fi
perl -pi -e "s#%PROJECTPATH%#$PROJECTPATH#g" $PROJECTPATH/site/config/config.ini


mkdir -p $PROJECTPATH/site/themes
cp -r $scriptPath/site/themes/default $PROJECTPATH/site/themes
